### ISSUE TITLE
Update CRC Cards

### ISSUE THREAD

**Issue by Logan9312** [CMPUT301W24T30/ScanPal#50]
Update CRC Cards with new data from our project.

AC:
- Inconsistent behavior between cards: Ex: Some cards still use permission level enum which we decided not to do, while other cards have the admin bool.
- Ensure collaborators are correct. Some were Missing or incorrect.
- Put a (Deprecated) tag on CRC cards that we do not plan to use and move them to the bottom of the page. For example we are not using UserDBConnector because we have UserController doing all of the database stuff now.

**Comment by Sundance636** [comment]
Just finished updating CRC cards and added the new stuff from latest merges
