### ISSUE TITLE
Upload event image

### ISSUE THREAD

**Issue by Logan9312** [CMPUT301W24T30/ScanPal#8]
US 01.04.01 As an organizer, I want to upload an event poster to provide visual information to attendees.

CheckList:
- [x] Implement 'Edit Image' button from add/edit event pages (only allow editing if organizer or Admin)
- [x] Allow uploading image from user device to firestorage
- [x] display image provided by user on event detail page

**Comment by Sundance636** [comment]
This issue has been Solved as a part of issue #63
